### PR TITLE
Added image saving

### PR DESCRIPTION
**Pull request by jaredmejia**
Added ability to save images on forward, left, right, backward push.

### CODE REVIEW

**Review by anthonyjclark — CHANGES_REQUESTED** [review]
We should just use `static_cast<RaycastWorld *>(glfwGetWindowUserPointer(window))->savePNG(...)` instead of using stb_image_write.h.

**Comment by jaredmejia** [comment]
Made requested change and added image saving for repeated events

**Review by anthonyjclark — CHANGES_REQUESTED** [review]
Make count a state variable.

Move saving images to a function.

Let user pass in the name of an image directory.

`savePNG` takes a `std::string`, so you don't need the `char* pngPath` variable.



Don't save images on key releases.

**Review by anthonyjclark — APPROVED** [review]
Looks good!

**Pull request merged**
